### ISSUE TITLE
utils.py file was missing

### ISSUE THREAD

**Issue by Leviplus** [xkmaxidian/MuCST#1]
Thank you for uploading such interesting work!
utils.py file was missing and please help fix it.

**Comment by xkmaxidian** [comment]
Thank you for bringing this to our attention. We apologize for the oversight of omitting this file from the initial upload. We have fixed the issue with the missing 'utils.py' file, and you can access it via 'https://github.com/xkmaxidian/MuCST/blob/master/utils.py'.
